#!/bin/bash

language=$1
filename=$2
problem=`echo $filename | tr [:upper:] [:lower:]`

if [ `echo $language | tr [:upper:] [:lower:]` == "java" ]; then
    javaFilename="$filename.java"

    mkdir ~/Kattis/Java/$problem
    cd ~/Kattis/Java/$problem
    ../../downloadSamples $problem
    touch $javaFilename
    cat >$javaFilename <<EOF
import java.util.Scanner;

public class ${filename} {
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);

    }
}
EOF
fi
