#!/bin/bash

language=$1
filename=$2
problem=`echo $filename | tr [:upper:] [:lower:]`

if [ `echo $language | tr [:upper:] [:lower:]` == "java" ]; then
    javaFilename="$filename.java"
    directory=~/Kattis/Java/$problem
    mkdir -p $directory
    cd $directory
    ../../downloadSamples $problem $directory
    touch $javaFilename
    cat >$javaFilename <<EOF
import java.util.Scanner;

public class ${filename} {
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);

    }
}
EOF
elif [ `echo $language | tr [:upper:] [:lower:]` == "python" ]; then
    pythonFilename="$filename.py"
    directory=~/Kattis/Python/$problem
    mkdir -p $directory
    cd $directory
    ../../downloadSamples $problem $directory
    touch $pythonFilename
fi
